language: node_js

node_js:
  - 0.8

before_script:
  - phantomjs --version
  - nohup python -m SimpleHTTPServer 8000 &

script:
  - ant -buildfile tools/build.xml
  - node tests/runner.js
  - phantomjs tools/phantom.js http://127.0.0.1:8000/tests/runner.html?console
